In [3]:
import numpy as np

In [4]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
array = np.random.randint(1, 11, size=(5, 5))
print(array)

[[ 6  9 10  2  5]
 [10  6 10  6  2]
 [ 4 10  4  8  2]
 [ 1  5  7  7  4]
 [ 4  8 10  9  3]]


In [6]:
array = np.random.rand(4, 4)
print(array)

[[0.48733801 0.85834441 0.6088608  0.03850682]
 [0.17650716 0.12132359 0.4779592  0.08651925]
 [0.92382758 0.43923498 0.57123587 0.4527921 ]
 [0.60704543 0.93419546 0.07322129 0.64757183]]


In [7]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

print("Перший масив:", array1)
print("Другий масив:", array2)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Результат додавання:", addition)
print("Результат віднімання:", subtraction)
print("Результат множення:", multiplication)

Перший масив: [3 7 9 6 6]
Другий масив: [3 3 1 8 3]
Результат додавання: [ 6 10 10 14  9]
Результат віднімання: [ 0  4  8 -2  3]
Результат множення: [ 9 21  9 48 18]


In [8]:

vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([8, 9, 10, 11, 12, 13, 14])

scalar_product = np.dot(vector1, vector2)

print("Скалярний добуток векторів:", scalar_product)

Скалярний добуток векторів: 336


In [9]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("Перша матриця (2x2):")
print(matrix1)
print("Друга матриця (2x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("Результат множення матриць:")
print(result)

Перша матриця (2x2):
[[ 5  9]
 [ 7 10]]
Друга матриця (2x3):
[[4 3 5]
 [8 1 2]]
Результат множення матриць:
[[ 92  24  43]
 [108  31  55]]


In [11]:
matrix = np.random.randint(1, 11, size=(3, 3))

print("Початкова матриця (3x3):")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Ця матриця є сингулярною (неможливо знайти обернену матрицю).")

Початкова матриця (3x3):
[[ 6  2  4]
 [ 5 10  3]
 [ 7  7  6]]
Обернена матриця:
[[ 0.51315789  0.21052632 -0.44736842]
 [-0.11842105  0.10526316  0.02631579]
 [-0.46052632 -0.36842105  0.65789474]]


In [12]:
matrix = np.random.rand(4, 4)

print("Початкова матриця (4x4):")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("Транспонована матриця:")
print(transposed_matrix)

Початкова матриця (4x4):
[[0.51908027 0.5669165  0.64659161 0.25096642]
 [0.93628841 0.23483557 0.02753528 0.34112271]
 [0.65278665 0.52916434 0.37497843 0.06814416]
 [0.33766714 0.18468387 0.84264827 0.95949294]]
Транспонована матриця:
[[0.51908027 0.93628841 0.65278665 0.33766714]
 [0.5669165  0.23483557 0.52916434 0.18468387]
 [0.64659161 0.02753528 0.37497843 0.84264827]
 [0.25096642 0.34112271 0.06814416 0.95949294]]


In [13]:
matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.randint(1, 11, size=4)

print("Матриця (3x4):")
print(matrix)
print("Вектор (розмір 4):")
print(vector)

result = np.dot(matrix, vector)

print("Результат перемноження матриці на вектор:")
print(result)


Матриця (3x4):
[[ 5  4 10 10]
 [ 9  3  2  6]
 [10  8  2  2]]
Вектор (розмір 4):
[9 2 9 7]
Результат перемноження матриці на вектор:
[213 147 138]


In [14]:
matrix = np.random.rand(2, 3)

vector = np.random.rand(3)

print("Матриця (2x3):")
print(matrix)
print("Вектор (розмір 3):")
print(vector)

result = np.dot(matrix, vector)

print("Результат перемноження матриці на вектор:")
print(result)

Матриця (2x3):
[[0.94512619 0.72395503 0.61095392]
 [0.72704329 0.882862   0.91048693]]
Вектор (розмір 3):
[0.0329062  0.49376106 0.45172017]
Результат перемноження матриці на вектор:
[0.66454153 0.87113242]


In [15]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша матриця (2x2):")
print(matrix1)
print("Друга матриця (2x2):")
print(matrix2)

elementwise_product = np.multiply(matrix1, matrix2)

print("Результат поелементного множення матриць:")
print(elementwise_product)

Перша матриця (2x2):
[[ 9  7]
 [10  3]]
Друга матриця (2x2):
[[1 9]
 [3 1]]
Результат поелементного множення матриць:
[[ 9 63]
 [30  3]]


In [16]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша матриця (2x2):")
print(matrix1)
print("Друга матриця (2x2):")
print(matrix2)

product = np.dot(matrix1, matrix2)

print("Результат добутку матриць:")
print(product)

Перша матриця (2x2):
[[9 6]
 [9 5]]
Друга матриця (2x2):
[[ 3 10]
 [10  5]]
Результат добутку матриць:
[[ 87 120]
 [ 77 115]]


In [17]:
matrix = np.random.randint(1, 101, size=(5, 5))

print("Матриця (5x5):")
print(matrix)

sum_of_elements = np.sum(matrix)

print("Сума елементів матриці:", sum_of_elements)

Матриця (5x5):
[[48 82 28 27 63]
 [78 15 21 73  3]
 [45 25 24  3 81]
 [ 9 59 91 54 87]
 [58 29 14 63 37]]
Сума елементів матриці: 1117


In [18]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Перша матриця (4x4):")
print(matrix1)
print("Друга матриця (4x4):")
print(matrix2)

difference = matrix1 - matrix2

print("Різниця матриць:")
print(difference)

Перша матриця (4x4):
[[ 9  2  3  1]
 [ 8  9 10  3]
 [ 5  5  6  1]
 [ 9 10  8 10]]
Друга матриця (4x4):
[[4 4 4 4]
 [4 1 6 1]
 [3 5 1 5]
 [9 1 3 1]]
Різниця матриць:
[[ 5 -2 -1 -3]
 [ 4  8  4  2]
 [ 2  0  5 -4]
 [ 0  9  5  9]]


In [19]:
matrix = np.random.rand(3, 3)

print("Матриця (3x3):")
print(matrix)

row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(3, 1)

print("Вектор-стовпчик із сумами елементів кожного рядка:")
print(column_vector)

Матриця (3x3):
[[0.48412267 0.29764462 0.39420277]
 [0.8035274  0.62603684 0.24921133]
 [0.97689304 0.70789668 0.70956643]]
Вектор-стовпчик із сумами елементів кожного рядка:
[[1.17597007]
 [1.67877557]
 [2.39435615]]


In [20]:
matrix = np.random.randint(1, 11, size=(3, 4))

print("Початкова матриця (3x4):")
print(matrix)

squared_matrix = np.square(matrix)

print("Матриця з квадратами чисел:")
print(squared_matrix)


Початкова матриця (3x4):
[[5 5 4 2]
 [2 5 2 8]
 [1 4 9 2]]
Матриця з квадратами чисел:
[[25 25 16  4]
 [ 4 25  4 64]
 [ 1 16 81  4]]


In [21]:
vector = np.random.randint(1, 51, size=4)

print("Початковий вектор:")
print(vector)

sqrt_vector = np.sqrt(vector)

print("Вектор з квадратними коренями:")
print(sqrt_vector)

Початковий вектор:
[46 34  5  9]
Вектор з квадратними коренями:
[6.78232998 5.83095189 2.23606798 3.        ]
